#!/usr/bin/fish

set SEL (/bin/ls -1 ~/.screenlayout | rofi -fullscreen -p "select" -dmenu -no-custom -no-click-to-exit 2>/dev/null)
if test -n "$SEL"
	bash ~/.screenlayout/"$SEL"
else
	echo "Nothing selected"
end
